version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: insightflow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: InsightFlowDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - insightflow-net

volumes:
  pgdata:

networks:
  insightflow-net:
    driver: bridge
